name: Upload Python Package to Test PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build-deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]

    runs-on: ${{ matrix.os }}
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build cibuildwheel twine 

      - name: Build binary python package
        run: |
          python -m build --sdist --outdir ./dist
          cibuildwheel --output-dir ./dist

      - name: List ./dist
        run: ls ./dist

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
